server:
  port: 8081

spring:
  application:
    name: api-usuarios
  datasource:
    url: jdbc:postgresql://db-usuarios:5432/postgres
    password: postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/